# Format code snippet included in doc comments.
format_code_in_doc_comments = true

# Format string literals where necessary.
format_strings = true

# Force multiline closure and match arm bodies to be wrapped in a block.
force_multiline_blocks = true

# Replace strings of _ wildcards by a single .. in tuple patterns.
condense_wildcard_suffixes = true

# Convert /* */ comments to // comments where possible.
normalize_comments = true

# Convert #![doc] and #[doc] attributes to //! and /// doc comments.
normalize_doc_attributes = true

# Reorder impl items. type and const are put first, then macros and methods.
reorder_impl_items = true

# Report FIXME items in comments.
report_fixme = "Always"

# Report TODO items in comments.
report_todo = "Always"

# Enable unstable features on the unstable channel.
unstable_features = true

# Replace uses of the try! macro by the ? shorthand.
use_try_shorthand = true

# Break comments to fit on the line.
wrap_comments = true
